import type { NextPage } from 'next'
import Head from 'next/head'
import { Hello } from '../components/Hello'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Custom Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        <Hello />
        Welcome to{' '}
        <a href="https://nextjs.org" target="_blank" rel="noreferrer">
          Next.js!
        </a>
      </h1>

      <div className={styles.grid}>
        <a href="https://nextjs.org/docs" target="_blank" rel="noreferrer" className={styles.card}>
          <h2>Documentation &rarr;</h2>
          <p>About Next.js features and API.</p>
        </a>
      </div>
    </main>

    <footer className={styles.footer}>
      <a href="https://github.com/ResTatic" target="_blank" rel="noreferrer">
        Customized by Res
      </a>
    </footer>
  </div>
)

export default Home
